export const VARIABLES = [
  'Warmth',
  'Moisture',
  'Tempest',
  'Upheaval',
  'Oceans',
  'Fertility',
  'Diversity',
  'Ingenuity',
  'Dominance',
];

export const STAGE_ORDER = [
  'Worldforming',
  'First Life',
  'Complex Life',
  'Great Creatures',
  'Thinking Beasts',
  'Civilization',
  'Ruin or Renewal',
];

export const STAGE_CONFIGS = {
  Worldforming: { goal: [12, 20], years: [35_000_000, 120_000_000], entropy: 0.16 },
  'First Life': { goal: [10, 18], years: [8_000_000, 30_000_000], entropy: 0.22 },
  'Complex Life': { goal: [14, 22], years: [2_000_000, 8_000_000], entropy: 0.32 },
  'Great Creatures': { goal: [12, 20], years: [300_000, 1_200_000], entropy: 0.46 },
  'Thinking Beasts': { goal: [10, 18], years: [50_000, 250_000], entropy: 0.64 },
  Civilization: { goal: [8, 15], years: [1_000, 20_000], entropy: 0.98 },
  'Ruin or Renewal': { goal: [6, 14], years: [50, 900], entropy: 1.42 },
};

export const SEVERITIES = [
  { key: 'light', label: 'Light', factor: 0.72 },
  { key: 'mild', label: 'Mild', factor: 1.0 },
  { key: 'strong', label: 'Strong', factor: 1.28 },
  { key: 'severe', label: 'Severe', factor: 1.58 },
];

const allStages = [...STAGE_ORDER];
const earlyStages = ['Worldforming', 'First Life', 'Complex Life'];
const livingStages = ['First Life', 'Complex Life', 'Great Creatures', 'Thinking Beasts', 'Civilization', 'Ruin or Renewal'];

const effectMap = (values) => {
  const full = {};
  for (const variable of VARIABLES) {
    full[variable] = values[variable] ?? 0;
  }
  return full;
};

const delayed = (range, effects, text) => ({
  delay: range,
  effects: effectMap(effects),
  text,
});

export const DECISION_TEMPLATES = [
  {
    id: 'rain-bands',
    label: 'Rain Bands',
    category: 'stabilizing',
    domain: 'Climate',
    stages: allStages,
    titleVariants: ['Rain Bands', 'Monsoon Rains', 'Cloud Rivers', 'Sky Showers', 'Wet Seasons'],
    subtitle: 'Moist air crosses waiting ground.',
    effects: effectMap({ Warmth: -2, Moisture: 4, Tempest: -1, Upheaval: -1, Oceans: 1, Fertility: 2, Diversity: 1, Ingenuity: 0, Dominance: -1 }),
    delayed: [delayed([2, 4], { Moisture: 1, Fertility: 2, Diversity: 1 }, 'Low ground stays rich after the gift.')],
    poetry: ['Clouds lower their burden.', 'Dry stone darkens.', 'The world softens.'],
  },
  {
    id: 'tidal-balance',
    label: 'Tidal Balance',
    category: 'stabilizing',
    domain: 'Oceans',
    stages: allStages,
    titleVariants: ['Tidal Balance', 'Gentle Tides', 'Coastal Pull', 'Shoreline Rhythm', 'Harboring Seas'],
    subtitle: 'The coasts learn a steadier pulse.',
    effects: effectMap({ Warmth: -1, Moisture: 2, Tempest: -2, Upheaval: -1, Oceans: 3, Fertility: 1, Diversity: 1, Ingenuity: 1, Dominance: -1 }),
    delayed: [delayed([2, 5], { Oceans: 1, Fertility: 1, Diversity: 1, Ingenuity: 1 }, 'Tidal flats become nurseries.')],
    poetry: ['The moon tugs with care.', 'Shore and sea trade ground.', 'Shelter appears.'],
  },
  {
    id: 'basin-carving',
    label: 'Basin Carving',
    category: 'stabilizing',
    domain: 'Geology',
    stages: earlyStages,
    titleVariants: ['Basin Carving', 'Valley Cutting', 'River Basins', 'Deep Channels', 'Catchment Plains'],
    subtitle: 'Stone is opened to hold water and silt.',
    effects: effectMap({ Warmth: 0, Moisture: 2, Tempest: -1, Upheaval: 1, Oceans: 1, Fertility: 3, Diversity: 0, Ingenuity: 1, Dominance: -1 }),
    delayed: [delayed([2, 4], { Fertility: 2, Diversity: 1, Upheaval: -1, Ingenuity: 1 }, 'Sediment settles where life can use it.')],
    poetry: ['Rivers remember the slope.', 'Stone yields a little.', 'Basins hold tomorrow.'],
  },
  {
    id: 'cloud-shield',
    label: 'Cloud Shield',
    category: 'stabilizing',
    domain: 'Atmosphere',
    stages: allStages,
    titleVariants: ['Cloud Shield', 'Sky Veil', 'Cooling Haze', 'Softened Sun', 'Pale Canopy'],
    subtitle: 'The light is gentled before it strikes.',
    effects: effectMap({ Warmth: -3, Moisture: 2, Tempest: -1, Upheaval: 0, Oceans: 0, Fertility: 1, Diversity: 1, Ingenuity: 0, Dominance: -1 }),
    delayed: [delayed([2, 5], { Warmth: -1, Moisture: 1, Diversity: 1 }, 'The softer climate lingers.')],
    poetry: ['The sky learns restraint.', 'Harsh light blurs.', 'Breathing grows easier.'],
  },
  {
    id: 'geothermal-nursery',
    label: 'Geothermal Nursery',
    category: 'stabilizing',
    domain: 'Geology',
    stages: ['Worldforming', 'First Life', 'Complex Life'],
    titleVariants: ['Geothermal Nursery', 'Warm Vents', 'Vented Seas', 'Heated Springs', 'Sheltered Vents'],
    subtitle: 'Heat is placed where fragile beginnings can endure.',
    effects: effectMap({ Warmth: 2, Moisture: 1, Tempest: -1, Upheaval: 2, Oceans: 1, Fertility: 2, Diversity: 1, Ingenuity: 0, Dominance: -1 }),
    delayed: [delayed([2, 4], { Fertility: 1, Diversity: 2, Upheaval: -1 }, 'Niches gather around the vents.')],
    poetry: ['Hidden warmth is spared from storm.', 'The deep keeps a quiet cradle.', 'Beginnings hold.'],
  },
  {
    id: 'ice-cap-growth',
    label: 'Ice Cap Growth',
    category: 'stabilizing',
    domain: 'Climate',
    stages: allStages,
    titleVariants: ['Ice Cap Growth', 'Polar Ice', 'Frozen Crown', 'Cold Caps', 'Glacial Margin'],
    subtitle: 'The poles draw heat away from the wide world.',
    effects: effectMap({ Warmth: -3, Moisture: 1, Tempest: -1, Upheaval: 0, Oceans: 0, Fertility: 1, Diversity: 0, Ingenuity: 0, Dominance: -1 }),
    delayed: [delayed([3, 5], { Warmth: -1, Oceans: -1, Fertility: 1 }, 'The cold stores water and patience.')],
    poetry: ['White silence gathers.', 'The world exhales heat.', 'Edges harden.'],
  },
  {
    id: 'reef-shelf-lift',
    label: 'Reef Shelf Lift',
    category: 'stabilizing',
    domain: 'Oceans',
    stages: livingStages,
    titleVariants: ['Reef Shelf Lift', 'Shallow Reefs', 'Coral Platforms', 'Shelf Bloom', 'Warm Shoals'],
    subtitle: 'Shallow seas spread broad feeding grounds.',
    effects: effectMap({ Warmth: 1, Moisture: 1, Tempest: -1, Upheaval: -1, Oceans: 2, Fertility: 2, Diversity: 2, Ingenuity: 1, Dominance: -1 }),
    delayed: [delayed([2, 4], { Diversity: 2, Fertility: 1, Oceans: 1, Ingenuity: 1 }, 'The shelves become nurseries of many forms.')],
    poetry: ['The shallows brighten.', 'Edges teem with mouths and color.', 'Abundance broadens.'],
  },
  {
    id: 'monsoon-shift',
    label: 'Monsoon Shift',
    category: 'ambiguous',
    domain: 'Climate',
    stages: allStages,
    titleVariants: ['Monsoon Shift', 'Seasonal Rains', 'Swinging Wet Season', 'Rain Turn', 'Moving Storm Season'],
    subtitle: 'Water arrives in one place and leaves another wanting.',
    effects: effectMap({ Warmth: 0, Moisture: 3, Tempest: 2, Upheaval: 0, Oceans: 1, Fertility: 1, Diversity: 1, Ingenuity: 0, Dominance: 0 }),
    delayed: [delayed([2, 4], { Moisture: -2, Fertility: 1, Ingenuity: 1, Dominance: 1 }, 'The wet season moves on and old rivals return.')],
    poetry: ['The sky changes its route.', 'Some valleys drink deeply.', 'Others are forgotten.'],
  },
  {
    id: 'jet-stream-bend',
    label: 'Jet Stream Bend',
    category: 'ambiguous',
    domain: 'Atmosphere',
    stages: allStages,
    titleVariants: ['Jet Stream Bend', 'Sky Current Shift', 'High Wind Turn', 'Air River Bend', 'Upper Wind Cut'],
    subtitle: 'Storm roads and calm belts are redrawn.',
    effects: effectMap({ Warmth: 1, Moisture: 1, Tempest: 3, Upheaval: 0, Oceans: 0, Fertility: 0, Diversity: 1, Ingenuity: 1, Dominance: 0 }),
    delayed: [delayed([2, 5], { Tempest: -2, Diversity: 1, Ingenuity: 1 }, 'Scattered seeds and survivors claim new ranges.')],
    poetry: ['High winds take a different road.', 'Clouds lose old habits.', 'Distance means something new.'],
  },
  {
    id: 'moon-tug',
    label: 'Moon Tug',
    category: 'ambiguous',
    domain: 'Cosmic',
    stages: allStages,
    titleVariants: ['Moon Tug', 'Orbital Pull', 'Lunar Heave', 'Tidal Moonrise', 'Silver Pull'],
    subtitle: 'The tides and seasons answer a stronger distant hand.',
    effects: effectMap({ Warmth: 0, Moisture: 1, Tempest: 1, Upheaval: 1, Oceans: 3, Fertility: 1, Diversity: 0, Ingenuity: 0, Dominance: 0 }),
    delayed: [delayed([3, 5], { Oceans: 1, Tempest: 1, Diversity: 1, Ingenuity: 1 }, 'Coasts change shape under repeated strain.')],
    poetry: ['The distant stone leans closer.', 'Waters climb farther inland.', 'Rhythm grows stronger.'],
  },
  {
    id: 'polar-thaw',
    label: 'Polar Thaw',
    category: 'ambiguous',
    domain: 'Climate',
    stages: allStages,
    titleVariants: ['Polar Thaw', 'Melting Caps', 'Thawing Ice', 'Opened Poles', 'Retreating Frost'],
    subtitle: 'Cold seas open, and the lowlands pay the price.',
    effects: effectMap({ Warmth: 3, Moisture: 2, Tempest: 1, Upheaval: 0, Oceans: 2, Fertility: 0, Diversity: 1, Ingenuity: 0, Dominance: 0 }),
    delayed: [delayed([2, 4], { Oceans: 1, Tempest: 1, Fertility: -1, Diversity: -1 }, 'The rising edge of water keeps taking.')],
    poetry: ['The frozen crown loosens.', 'Cold waters break apart.', 'Shorelines become uncertain.'],
  },
  {
    id: 'ash-veil',
    label: 'Ash Veil',
    category: 'ambiguous',
    domain: 'Geology',
    stages: allStages,
    titleVariants: ['Ash Veil', 'Volcanic Dust', 'Darkened Sky', 'Ashfall', 'Soot Haze'],
    subtitle: 'The sky darkens, then the soil remembers.',
    effects: effectMap({ Warmth: -1, Moisture: 0, Tempest: 1, Upheaval: 2, Oceans: 0, Fertility: 1, Diversity: 0, Ingenuity: 0, Dominance: 0 }),
    delayed: [delayed([2, 5], { Fertility: 2, Diversity: 1, Upheaval: -1 }, 'Ash settles into black nourishment.')],
    poetry: ['Light grows dim.', 'Breathing turns harder.', 'Later, the soil will answer.'],
  },
  {
    id: 'inland-sea-breach',
    label: 'Inland Sea Breach',
    category: 'ambiguous',
    domain: 'Oceans',
    stages: allStages,
    titleVariants: ['Inland Sea Breach', 'Saltwater Inlet', 'Broken Isthmus', 'Open Basin Sea', 'Flooded Interior'],
    subtitle: 'Water enters the heartland and changes every border.',
    effects: effectMap({ Warmth: 1, Moisture: 2, Tempest: 1, Upheaval: 1, Oceans: 3, Fertility: 1, Diversity: 1, Ingenuity: 1, Dominance: 1 }),
    delayed: [delayed([2, 4], { Fertility: -1, Diversity: 1, Ingenuity: 1, Dominance: 1 }, 'New coasts bring crowded competition.')],
    poetry: ['The interior drowns in salt.', 'New shores appear overnight.', 'Old territories vanish.'],
  },
  {
    id: 'rift-valley-opening',
    label: 'Rift Valley Opening',
    category: 'ambiguous',
    domain: 'Geology',
    stages: allStages,
    titleVariants: ['Rift Valley Opening', 'Fresh Rift', 'Split Valley', 'Young Chasm', 'Breaking Plateau'],
    subtitle: 'New edges form, and new hazards with them.',
    effects: effectMap({ Warmth: 1, Moisture: 1, Tempest: 1, Upheaval: 3, Oceans: 0, Fertility: 1, Diversity: 1, Ingenuity: 2, Dominance: 0 }),
    delayed: [delayed([2, 5], { Fertility: 2, Diversity: 1, Upheaval: -1, Ingenuity: 1 }, 'Minerals and microclimates gather along the wound.')],
    poetry: ['The crust parts.', 'Shelter and danger share a border.', 'The wound attracts life.'],
  },
  {
    id: 'crust-fracture',
    label: 'Crust Fracture',
    category: 'destabilizing',
    domain: 'Geology',
    stages: allStages,
    titleVariants: ['Crust Fracture', 'Major Rift', 'Shattered Plate', 'Tectonic Break', 'Broken Crust'],
    subtitle: 'Stone rejects stillness and opens deep wounds.',
    effects: effectMap({ Warmth: 2, Moisture: -2, Tempest: 2, Upheaval: 4, Oceans: -1, Fertility: -2, Diversity: -1, Ingenuity: 0, Dominance: 1 }),
    delayed: [delayed([3, 5], { Fertility: 2, Upheaval: -1, Diversity: 1 }, 'The torn crust later exposes rich new minerals.')],
    poetry: ['The ground lurches.', 'Mountains rise where none were asked for.', 'Certainty splits.'],
  },
  {
    id: 'volcanic-arc',
    label: 'Volcanic Arc',
    category: 'destabilizing',
    domain: 'Geology',
    stages: allStages,
    titleVariants: ['Volcanic Arc', 'Fire Chain', 'Magma Belt', 'Eruption Line', 'Burning Highlands'],
    subtitle: 'Fire crowns the horizon with repeated violence.',
    effects: effectMap({ Warmth: 3, Moisture: -1, Tempest: 2, Upheaval: 3, Oceans: 0, Fertility: -1, Diversity: -1, Ingenuity: 0, Dominance: 1 }),
    delayed: [delayed([2, 4], { Fertility: 2, Diversity: 1, Upheaval: -1 }, 'Ash cools into future abundance.')],
    poetry: ['Fire walks a line across the land.', 'Ash blinds the day.', 'The price comes first.'],
  },
  {
    id: 'desert-winds',
    label: 'Desert Winds',
    category: 'destabilizing',
    domain: 'Climate',
    stages: allStages,
    titleVariants: ['Desert Winds', 'Dry Gales', 'Dust Storms', 'Scouring Air', 'Parched Winds'],
    subtitle: 'Moisture is stripped from root, sea edge, and skin.',
    effects: effectMap({ Warmth: 2, Moisture: -4, Tempest: 2, Upheaval: 0, Oceans: -1, Fertility: -2, Diversity: -1, Ingenuity: 0, Dominance: 1 }),
    delayed: [delayed([2, 5], { Moisture: -1, Fertility: -1, Dominance: 1 }, 'The ground keeps cracking after the storm has passed.')],
    poetry: ['The air grows sharp and empty.', 'Dust takes the place of rain.', 'Only the hard rejoice.'],
  },
  {
    id: 'storm-front',
    label: 'Storm Front',
    category: 'destabilizing',
    domain: 'Climate',
    stages: allStages,
    titleVariants: ['Storm Front', 'Cyclone Season', 'Tempest Wall', 'Violent Weather', 'Black Squalls'],
    subtitle: 'Violence moves with the clouds and keeps moving.',
    effects: effectMap({ Warmth: 0, Moisture: 2, Tempest: 4, Upheaval: 1, Oceans: 1, Fertility: -1, Diversity: -1, Ingenuity: 0, Dominance: 1 }),
    delayed: [delayed([2, 4], { Tempest: 1, Moisture: 1, Diversity: -1 }, 'The pattern repeats before recovery can settle.')],
    poetry: ['The horizon darkens in ranks.', 'Wind arrives before thought.', 'Shelter is tested.'],
  },
  {
    id: 'methane-surge',
    label: 'Methane Surge',
    category: 'destabilizing',
    domain: 'Atmosphere',
    stages: allStages,
    titleVariants: ['Methane Surge', 'Heat Burst', 'Gas Release', 'Greenhouse Surge', 'Boiling Air'],
    subtitle: 'Heat is trapped and the seasons lose discipline.',
    effects: effectMap({ Warmth: 4, Moisture: 1, Tempest: 2, Upheaval: 0, Oceans: 0, Fertility: -2, Diversity: -1, Ingenuity: 0, Dominance: 1 }),
    delayed: [delayed([2, 5], { Warmth: 2, Tempest: 1, Fertility: -1 }, 'The air keeps holding more heat than it should.')],
    poetry: ['The sky keeps too much warmth.', 'Seasons blur and swell.', 'Balance retreats.'],
  },
  {
    id: 'floodplain-break',
    label: 'Floodplain Break',
    category: 'destabilizing',
    domain: 'Oceans',
    stages: allStages,
    titleVariants: ['Floodplain Break', 'Levee Failure', 'River Overrun', 'Broken Banks', 'Runaway Flood'],
    subtitle: 'Water leaves its channel and redraws the map by force.',
    effects: effectMap({ Warmth: -1, Moisture: 3, Tempest: 2, Upheaval: 1, Oceans: 1, Fertility: -2, Diversity: -2, Ingenuity: 0, Dominance: 1 }),
    delayed: [delayed([2, 4], { Fertility: 2, Moisture: 1, Diversity: 1 }, 'Silt remains where the waters finally retreat.')],
    poetry: ['The river forgets its oath.', 'Low ground disappears.', 'Later, the mud will feed someone else.'],
  },
];

export const SPECIES_POOLS = {
  habitats: {
    aquatic: ['Reef Schools', 'Shellbacks', 'River Striders', 'Glass Eels', 'Tide Grazers'],
    amphibious: ['Marsh Walkers', 'Delta Crawlers', 'Reed Hunters', 'Bog Striders', 'Shore Herders', 'Marsh Scarabs'],
    terrestrial: ['Stonebacks', 'Plain Runners', 'Forest Grazer Clans', 'Dune Sloths', 'Tall Browsers', 'Mound Beetles'],
    aerial: ['Gliders', 'Sky Kites', 'Storm Wings', 'Ash Moths', 'Cloud Herons', 'Locust Veils'],
    subterranean: ['Burrow Hives', 'Mole Houses', 'Root Burrowers', 'Deep Ants', 'Tunnel Herds', 'Beetle Choirs', 'Chitin Swarms'],
  },
  behaviors: {
    Cooperation: ['choral', 'pack bound', 'nest sharing', 'kin woven', 'hive bound'],
    Aggression: ['predatory', 'territorial', 'raiding', 'crowned by violence'],
    Adaptability: ['migratory', 'quick changing', 'opportunistic', 'broad feeding'],
    Curiosity: ['tool minded', 'pattern watching', 'experimenting', 'far seeing', 'signal reading'],
    Resilience: ['plated', 'hard shelled', 'storm tested', 'long enduring'],
  },
};

export const CIVILIZATION_SUFFIXES = ['League', 'Compact', 'Dominion', 'Archive', 'Choir', 'Forum', 'Remnant'];
export const SWARM_SUFFIXES = ['Swarm', 'Brood', 'Nest', 'Synod', 'Hive'];

export const FINAL_LINES = [
  'The world is quiet again.',
  'What lived has returned to dust.',
  'It endured, but not forever.',
  'The long struggle has ended.',
];
